# Generated by Django 3.1.7 on 2021-03-04 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_like'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='author',
            new_name='author_comment',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='dislikes_count',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='likes_count',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='updated',
        ),
        migrations.RemoveField(
            model_name='like',
            name='count',
        ),
    ]
