# Generated by Django 3.1.7 on 2021-03-10 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0005_auto_20210308_1147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='author_comment',
            field=models.CharField(max_length=50),
        ),
    ]
